# Manejo de excepciones

## 1.8.1 Excepciones en Python
- Las excepciones son eventos que ocurren durante la ejecución de un programa cuando se encuentra un error o una situación inusual.
- Cuando ocurre una excepción, el flujo normal del programa se interrumpe y, si no se maneja adecuadamente, el programa puede terminar de forma inesperada.

## 1.8.2 Manejo de excepciones con try y except
- El manejo de excepciones en Python se realiza utilizando bloques de código `try` y `except`.
- El código que puede generar una excepción se coloca dentro del bloque `try`.
- Si ocurre una excepción en el bloque `try`, el flujo del programa se traslada al bloque `except` correspondiente, donde se puede manejar la excepción o realizar acciones de limpieza.

Ejemplo de manejo de excepciones:## 

```python
try:
    number = int(input("Enter a number: "))
    result = 10 / number
except ValueError:
    print("Invalid input. Please enter a number.")
except ZeroDivisionError:
    print("Cannot divide by zero.")
else:
    print(f"Result: {result}")
```

## 1.8.3 Bloque finally
- El bloque `finally` se utiliza para especificar acciones que deben realizarse independientemente de si ocurre una excepción o no.
- El código dentro del bloque `finally` se ejecutará siempre, incluso si hay un `return` en el bloque `try` o `except`.

Ejemplo de bloque finally:

```python
try:
    number = int(input("Enter a number: "))
    result = 10 / number
except ValueError:
    print("Invalid input. Please enter a number.")
except ZeroDivisionError:
    print("Cannot divide by zero.")
else:
    print(f"Result: {result}")
finally:
    print("This message will always be displayed.")
```

## 1.8.4 Levantando excepciones
- Puedes levantar tus propias excepciones utilizando la palabra clave `raise`, seguida de la excepción que deseas lanzar y, opcionalmente, un mensaje de error personalizado.

Ejemplo de levantamiento de excepciones:

```python
def validate_age(age):
    if age < 0:
        raise ValueError("Age cannot be negative.")

try:
    validate_age(-5)
except ValueError as e:
    print(f"Error: {e}")
```

El manejo adecuado de excepciones es importante para garantizar que los programas sean robustos y puedan manejar errores y situaciones inesperadas de manera elegante. En las siguientes secciones, se abordarán temas más avanzados como las clases y objetos en Python y las bibliotecas estándar de Python.